GET http://127.0.0.1:8000/users/
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY0MDI1NDQ5LCJqdGkiOiJhOGQ5ZWU3NjhhYTk0ZDk0YjRiMzMyMTc2MjU5OThkYiIsInVzZXJfaWQiOjF9.y3H_BTdCQqWpWikTvG9iX7emVRUp6nMMnBDWaZJGi-s
###
POST http://127.0.0.1:8000/auth/jwt/create/
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

### USERS
GET http://127.0.0.1:8000/users/
content-type: application/json
Authorization: Bearer 

### AUTH DJOSER
GET http://127.0.0.1:8000/auth/users/me/
content-type: application/json
Authorization: Bearer 
### CREATE USER
POST http://127.0.0.1:8000/auth/users/
content-type: application/json

{
    "username": "user2",
    "password": "@Pplec0m"
}

### CATS
POST http://127.0.0.1:8000/cats/
content-type: application/json
Authorization: Bearer 

{
    "name": "Мурка",
    "color": "Mixed",
    "birth_year": 2017
}
### CATS DELETE
DELETE http://127.0.0.1:8000/cats/4/
content-type: application/json
Authorization: Bearer 

